kf/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.defaults import page_not_found
from search import views as search_views
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.core import views as wagtail_views
from wagtail.core.urls import WAGTAIL_FRONTEND_LOGIN_TEMPLATE, serve_pattern
from wagtail.documents import urls as wagtaildocs_urls
from wagtailcache.cache import cache_page

urlpatterns = [
    path('django-admin/', admin.site.urls),

    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),

    path('search/', search_views.search, name='search'),

    path("email/", page_not_found, kwargs={"exception": Exception("Page not Found")},), # prevent email management (changing/removing)
    path(r'', include('allauth.urls')),
    path("", include("shop.urls")),

]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:

    # path("", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),

    url(r'^_util/authenticate_with_password/(\d+)/(\d+)/$', wagtail_views.authenticate_with_password,
        name='wagtailcore_authenticate_with_password'),
    url(r'^_util/login/$', auth_views.LoginView.as_view(template_name=WAGTAIL_FRONTEND_LOGIN_TEMPLATE),
        name='wagtailcore_login'),

    # Wrap the serve function with wagtail-cache
    url(serve_pattern, cache_page(wagtail_views.serve), name='wagtail_serve'),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, re_path

from . import views

app_name = 'shop'
urlpatterns = [
    path("shop/additem/", views.additem, name="additem"),
    path("shop/removeitem/", views.removeitem, name="removeitem"),
    path("shop/removecartitem/", views.removecartitem, name="removecartitem"),
    path("shop/checkout/", views.checkout, name="checkout"),
    path("shop/recent_orders/", views.recent_orders, name="recent_orders"),
    path("shop/checkout/", views.checkout, name="checkout"),
    path("shop/payment/", views.payment, name="payment"),
    path("shop/addaddress/", views.addaddress, name="addaddress"),
    path("shop/removeaddress/", views.removeaddress, name="removeaddress"),
    path("shop/order/<int:id>/", views.order_success, name="order-success"),
    path("shop/email_preview/<int:id>/", views.email_preview, name="email_preview"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),

]

kf/templates/base.html
{% load static wagtailuserbar wagtailcore_tags %}

<!DOCTYPE html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8" />
        <title>
            {% block title %}
                {% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}
            {% endblock %}
            {% block title_suffix %}
                {% with self.get_site.site_name as site_name %}
                    {% if site_name %}- {{ site_name }}{% endif %}
                {% endwith %}
            {% endblock %}
        </title>
        <meta name="description" content="" />
        <!-- <meta name="viewport" content="width=device-width, initial-scale=1" /> -->
        <meta id="Viewport" name="viewport" content="initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">

        <link rel="shortcut icon" type="image/jpg" href="{% static 'kf.svg' %}"/>


        {# Global stylesheets #}
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

        <link href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css" rel="stylesheet"/>

        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;600&display=swap" rel="stylesheet">

        

        <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css">        

        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">


        <link rel="stylesheet" type="text/css" href="{% static 'css/viewer.css' %}">
        
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
        <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
        <script src="{% static 'js/infinite.min.js' %}"></script>


        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}


        {% block extra_header_js %}

            {# ex. Braintree asks to put their code in head #}

        {% endblock %}
    </head>

    <body class="{% block body_class %}{% endblock %}">

        <nav class="navbar navbar-expand-md navbar-dark bg-primary">

            <div class="mx-auto order-0">
                <a class="navbar-brand mx-auto" href="/">Kayleigh Fichten <span class="d-none d-sm-inline">Studio</span></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>

<!--             <a class="navbar-brand" href="/">Kayleigh Fichten <span class="d-none d-sm-inline">Studio</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button> -->
            <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2 ">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item ml-1 {% if '/gallery'  in request.path %}active{% endif %}">
                        <a class="nav-link" href="/gallery">Gallery{% if '/gallery'  in request.path %}<span class="sr-only">(current)</span>{% endif %}</a>
                    </li>
                    <li class="nav-item ml-1 {% if '/shop'  in request.path and '/cart' not in request.path %}active{% endif %}">
                        <a class="nav-link" href="/shop">Shop {% if '/shop' in request.path and '/cart' not in request.path %}<span class="sr-only">(current)</span>{% endif %}</a>
                    </li>
                    <li class="nav-item ml-1 {% if '/contact'  in request.path %}active{% endif %}">
                        <a class="nav-link" href="/contact">Contact{% if '/contact'  in request.path %}<span class="sr-only">(current)</span>{% endif %}</a>
                    </li>
                </ul>
            </div>

            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto ">
                    
                    <li class="cart-nav nav-item ml-1 {% if request.session.cart|length < 1 %}d-none{% endif %}  {% if '/cart' in request.path %}active{% endif %}">
                        <a class="cart-nav-text nav-link" href="/shop/cart">Cart({{ request.session.cart|length }}){% if '/cart'  in request.path %}<span class="sr-only">(current)</span>{% endif %}</a>
                    </li>
                   
                    <li class="nav-item ml-1">
                        {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown ml-auto">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> My account </a>
                            <div class="dropdown-menu dropdown-menu-right text-md-right" aria-labelledby="navbarDropdownMenuLink">
                                <div class="text-primary dropdown-item">{{ request.user.username }}</div>
                                <a class="dropdown-item" href="/shop/profile">My Profile</a>
                                <a class="dropdown-item" href="{% url 'shop:recent_orders' %}">My Recent orders</a>
                                {% if request.user.is_superuser %}
                                <a class="dropdown-item" href="/admin">Website admin</a>
                                {% endif %}
                                <a class="dropdown-item" href="/logout">Logout</a>
                            </div>
                        </li>
                        {% else %}
                        <a href="/login" class="nav-link">Login</a>
                        {% endif %}
                    </li>
                    
                </ul>
            </div>
        </nav>

        <div class="row">
            <div class="col-12">
            {% for error in errors %}
                <div class="row flex-row justify-content-center my-3">
                        <div class="text-danger alert alert-dismissible" role="alert">
                            <strong> {{ error }} 
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </strong>
                        </div>
                </div>
            {% endfor %}   
            </div>
        </div>

           {% block body %} {% block content %}{% endblock %}{% endblock %}

        {# Global javascript #}
    
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/viewerjs/1.6.1/viewer.js" integrity="sha512-McWjPxHtT2wRRn8GaTeCGnIefQxGWsIW75wBkefZADRobsuOnJx+fGZtZO/KzQ3BXgyBSzwMJ4jvrdwaC5G3/g==" crossorigin="anonymous"></script>
        <script src="https://unpkg.com/@popperjs/core@2.4.4/dist/umd/popper.min.js"></script>

        <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
                
        <script>
            var numGalleryItems = {{ page.gallery_images.all|length }}
            var numHomePageImages = {{ page.home_page_images.all|length }}
            var numImages = numGalleryItems || numHomePageImages
            var cartItems = {% if request.session.cart %}{{ request.session.cart }}{% else %}[]{% endif %}
            var pageId = {% if item %}{{ item.id }}{% elif page %}{{ page.id }}{% else %}'no such id'{% endif %}
        </script>


        <script type="module" src="{% static 'js/main.js' %}"></script>
        <script type="module" src="{% static 'js/viewerjs.js' %}"></script>




        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}
    </body>
</html>

kf/templates/skeleton.html
{% extends "wagtailadmin/skeleton.html" %}

{% block branding_title %}KF{% endblock %} - {% block titletag %}{% endblock %}