kf/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.defaults import page_not_found
from search import views as search_views
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.core import views as wagtail_views
from wagtail.core.urls import WAGTAIL_FRONTEND_LOGIN_TEMPLATE, serve_pattern
from wagtail.documents import urls as wagtaildocs_urls
from wagtailcache.cache import cache_page

urlpatterns = [
    path('django-admin/', admin.site.urls),

    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),

    path('search/', search_views.search, name='search'),

    path("email/", page_not_found, kwargs={"exception": Exception("Page not Found")},), # prevent email management (changing/removing)
    path(r'', include('allauth.urls')),
    path("", include("shop.urls")),

]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:

    # path("", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),

    url(r'^_util/authenticate_with_password/(\d+)/(\d+)/$', wagtail_views.authenticate_with_password,
        name='wagtailcore_authenticate_with_password'),
    url(r'^_util/login/$', auth_views.LoginView.as_view(template_name=WAGTAIL_FRONTEND_LOGIN_TEMPLATE),
        name='wagtailcore_login'),

    # Wrap the serve function with wagtail-cache
    url(serve_pattern, cache_page(wagtail_views.serve), name='wagtail_serve'),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, re_path

from . import views

app_name = 'shop'
urlpatterns = [
    path("shop/additem/", views.additem, name="additem"),
    path("shop/removeitem/", views.removeitem, name="removeitem"),
    path("shop/removecartitem/", views.removecartitem, name="removecartitem"),
    path("shop/checkout/", views.checkout, name="checkout"),
    path("shop/recent_orders/", views.recent_orders, name="recent_orders"),
    path("shop/checkout/", views.checkout, name="checkout"),
    path("shop/payment/", views.payment, name="payment"),
    path("shop/addaddress/", views.addaddress, name="addaddress"),
    path("shop/removeaddress/", views.removeaddress, name="removeaddress"),
    path("shop/order/<int:id>/", views.order_success, name="order-success"),
    path("shop/email_preview/<int:id>/", views.email_preview, name="email_preview"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),

]

shop/views.py
import json
from decimal import Decimal

import braintree
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import (Http404, HttpResponse, HttpResponseRedirect,
                         JsonResponse)
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from gallery.models import GalleryItem
from myforms.models import AddressForm
from slugify import slugify
from wagtailcache.cache import nocache_page

from .models import Cart, Order, UserAddress

if settings.BRAINTREE_PRODUCTION:
    braintree_env = braintree.Environment.Production
else:
    braintree_env = braintree.Environment.Sandbox
    print("Using Braintree sandbox environment.")


gateway = braintree.BraintreeGateway(
    braintree.Configuration(
        braintree_env,
        merchant_id=settings.BRAINTREE_MERCHANT_ID,
        public_key=settings.BRAINTREE_PUBLIC_KEY,
        private_key=settings.BRAINTREE_PRIVATE_KEY
    )
)


def email_preview(request, id):
    order = Order.objects.get(pk=id)
    return render(request, 'shop/order_confirmation.html', {'order': order})


@csrf_exempt
def additem(request):
    itemId = json.loads(request.POST['itemId'])
    cart = request.session.get('cart', [])
    if(itemId not in cart):
        try:
            cart.append(itemId)
            request.session['cart'] = cart
        except Exception:
            pass
    data = {'cart': request.session['cart']}
    print(request.session['cart'])
    return JsonResponse(data)


@csrf_exempt
def removeitem(request):
    itemId = json.loads(request.POST['itemId'])
    cart = request.session.get('cart', [])
    if(itemId in cart):
        try:
            cart.remove(itemId)
            request.session['cart'] = cart
        except Exception:
            pass
    data = {'cart': request.session['cart']}
    print(request.session['cart'])
    return JsonResponse(data)


@csrf_exempt
def removecartitem(request):
    itemId = json.loads(request.POST['itemId'])
    cart = request.session.get('cart', [])
    if(itemId in cart):
        try:
            cart.remove(itemId)
            request.session['cart'] = cart
            print('cart item removed')
        except Exception:
            print('exception found!!!!')
            pass
    items = GalleryItem.objects.filter(pk__in=request.session['cart'])
    total = Decimal(0.00)
    for item in items:
        total += item.direct_sale_price
    data = {'cart': request.session['cart'], 'total': total}
    return JsonResponse(data)


def recent_orders(request):
    orders = Order.objects.filter(user=request.user).order_by('-date')
    return render(request, 'shop/recent_orders.html', {'orders': orders})

@nocache_page
@login_required
def checkout(request):
    items = GalleryItem.objects.filter(pk__in=request.session['cart'])
    errors = []
    total = Decimal(0.00)
    for item in items:
        # Now done with context_processor
        # if item.stock == 0:
        #     request.session['cart'].remove(item.pk)
        #     request.session.modified = True
        #     errors.append(f'{item.title} ({item.direct_sale_price}) is no longer in stock and was removed from your cart.')
        # else:
        total += item.direct_sale_price
    items = GalleryItem.objects.filter(pk__in=request.session['cart'])

    if not request.session['cart']:
        return render(request, 'shop/cart.html', {'errors': errors})

    try:
        # Always fails, probably doesn't work with Checkout flow (vs. Vault with saved payment methods)
        braintree_client_token = gateway.client_token.generate(
            {"customer_id": request.user.id})
    except:
        braintree_client_token = gateway.client_token.generate({})

    context = {
        'braintree_client_token': braintree_client_token,
        'cart': items,
        'order_total': total,
        'address_form': AddressForm(),
        'errors': errors,
        'user_addresses': UserAddress.objects.filter(user=request.user, active=True)
    }
    return render(request, 'shop/checkout.html', context)


@login_required
def payment(request):

    errors = []

    print(request.POST)
    items = request.session['cart']

    order = Order(
        status='processing',
        user=request.user,
        shipping_address=UserAddress.objects.get(pk=request.POST['address']),
        first_name=request.POST['first-name'],
        last_name=request.POST['last-name'],

    )
    order.save()  # Get an ID to add items

    form_total = Decimal(request.POST['order-total'])
    db_total = Decimal(0.00)
    for item in items:
        obj = GalleryItem.objects.get(pk=item)
        order.items.add(obj)
        db_total += obj.direct_sale_price
    print(db_total)
    print(form_total)

    # Braintree requires total to be displayed on checkout page.
    # Ensure the form value was not tampered with, or in case the
    # db price has changed, then throw an error .
    if db_total == form_total:
        order.total = db_total
        order.save()
    else:
        errors.append("The order amount was not authorized by the server.")
        return render(request, 'shop/cart.html', {'errors': errors})

    nonce_from_the_client = request.POST['paymentMethodNonce']

    result = gateway.transaction.sale({
        "amount": request.POST['order-total'],
        "payment_method_nonce": nonce_from_the_client,
        "options": {
            "submit_for_settlement": True
        }
    })

    if result.is_success:

        order.status = 'success'
        order.paypal_id = result.transaction.id
        order.save()
        for item in order.items.all():
            item.stock -= 1
            if item.stock == 0:
                item.direct_sale = False
            item.save()
        request.session['cart'] = []

        order_item_details = ""

        for item in order.items.all():
            order_item_details += f"""
    {item.title}
    {item.description}
    ${item.direct_sale_price}

"""
        html_context = {
            'base_url': settings.BASE_URL,
            'order': order,
            }
        html_message = render_to_string('shop/order_confirmation.html', html_context)
        try:
            send_mail(
                f'Order confirmation #{order.id} from Kayleigh Fichten Studio',
                f"""Thank you for placing your order with Kayleigh Fichten Studio!

Your Confirmation #: {order.id}

Order details:
{ order_item_details }

Total: ${order.total}
Date placed: {order.date}

Ship to:
{order.formatted_shipping_address}


--

{settings.BASE_URL}""",
                settings.DEFAULT_FROM_EMAIL,
                [order.user.email, 'get@jeffkelly.dev'],
                html_message = html_message,
                fail_silently=False,
            )
        except ConnectionResetError:
            print('failed to send email confirmation message')

        return redirect('shop:order-success', id=order.id)

    elif result.errors.deep_errors:
        return JsonResponse({'result': str(result.errors.deep_errors)})
    else:
        return JsonResponse({'result': {
            'code': result.transaction.processor_settlement_response_code,
            'text': result.transaction.processor_settlement_response_text
        }
        })


@nocache_page
def order_success(request, id):
    # try:
    order = Order.objects.get(pk=id)
    return render(request, 'shop/order_success.html', {'order': order})
    # except:
    # return render(request, 'shop/order_success.html', {'errors': ['This order could not be found.']})


@login_required
def addaddress(request):
    all_addresses = []
    result = json.loads(request.POST['address'])
    remapCols = {
        'raw': 'formatted_address', 'street_number': 'street_number', 'route': 'route', 'locality': 'locality',
        'postal_code': 'postal_code', 'state': 'administrative_area_level_1', 'state_code': 'administrative_area_level_1_short',
        'country': 'country', 'country_code': 'country_short', 'latitude': 'lat', 'longitude': 'lng'}
    address = {}
    for key, value in remapCols.items():
        address[key] = result[value]
    is_new = True
    address_formatted = address['raw'] + ', ' + request.POST['address2'] if len(
        request.POST['address2']) is not None else address['raw']

    for a in UserAddress.objects.filter(user=request.user):
        if a.formatted == address_formatted:
            all_addresses.append(
                {'address': a.formatted, 'id': a.id, 'selected': True})
            a.active = True
            a.save()
            is_new = False
        elif a.active == True:
            all_addresses.append(
                {'address': a.formatted, 'id': a.id, 'selected': False})
    if is_new:
        a = UserAddress(user=request.user, address=address,
                        address2=request.POST['address2'])
        a.save()
        all_addresses.append(
            {'address': a.formatted, 'id': a.id, 'selected': True})

    data = {'addresses': all_addresses}
    return JsonResponse(data)


@login_required
@csrf_exempt
def removeaddress(request):
    print(request.POST)
    adr_id = request.POST['id']
    adr = UserAddress.objects.get(pk=adr_id)
    adr.active = False
    adr.save()
    data = {'result': 'success', 'id': adr_id}
    return JsonResponse(data)
    # except Exception as e:
    #     data = {'result': 'failed', 'error': str(e)}
    #     return JsonResponse(data)


@nocache_page
def privacy_policy(request):
    return render(request, 'shop/privacy_policy.html')

shop/templates/shop/cart.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags static %}
{% block body_class %}template-gallerypage{% endblock %}

{% block extra_header_js %}
{% endblock %}
{% block extra_js %}
{% endblock %}
    

{% block content %}



<div class="container">
    <div class="row ">

        <div class="col-12 ">
            <div class="row">
                <div class="col text-center">
                    <h1 class="page-title">Cart</h1>
                </div>
            </div>

            <hr class="my-4">
             
                <div class="row flex-row justify-content-center" id="cart-list"> 

{% for item in cart %}
                    <div class="col-6 col-md-4 mb-3 item-{{ item.pk }}" >
                    {% image item.main_image height-250 class="float-right img-fluid" %}
                    </div>
                    <div class="col-3 col-md-4 item-{{ item.pk }}">
                        <div class="">
                        <p> {{ item.title }} </p>
                        <p class="d-none d-sm-block"> {{ item.description|default_if_none:"" }} </p>
                        <p class="d-none d-sm-block"> {{ item.direct_sale_extra_description|default_if_none:"" }} </p>
                        <p class="d-none d-sm-block"> {{ item.sale_disclaimer|default_if_none:"" }} </p>
                        </div>
                        <div class="">


        <form method="post" class="remove-cart-item" data-item-id="{{ item.pk }}">
            {% csrf_token %}
        <input type="hidden"  name="itemId" value="{{ item.pk }}">
        <button type="submit" class="remove-cart-item-button btn btn-link" onsubmit="return false">Remove from cart</button>
        </form>


                            
                        </div>
                        <a tabindex="0" class="d-block d-sm-none"
                        data-toggle="popover" title="Item details" data-placement="bottom" data-trigger="focus"  data-content="{{ item.description }} {{ item.direct_sale_extra_description }} {{ item.sale_disclaimer }}"><u>Tap for details</u><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-question-circle-fill d-inline" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                          <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.496 6.033a.237.237 0 0 1-.24-.247C5.35 4.091 6.737 3.5 8.005 3.5c1.396 0 2.672.73 2.672 2.24 0 1.08-.635 1.594-1.244 2.057-.737.559-1.01.768-1.01 1.486v.105a.25.25 0 0 1-.25.25h-.81a.25.25 0 0 1-.25-.246l-.004-.217c-.038-.927.495-1.498 1.168-1.987.59-.444.965-.736.965-1.371 0-.825-.628-1.168-1.314-1.168-.803 0-1.253.478-1.342 1.134-.018.137-.128.25-.266.25h-.825zm2.325 6.443c-.584 0-1.009-.394-1.009-.927 0-.552.425-.94 1.01-.94.609 0 1.028.388 1.028.94 0 .533-.42.927-1.029.927z"/>
                        </svg>
                        </a>

                    </div>

                    <div class="col-3 col-md-4 item-{{ item.pk }}">

                    ${{ item.direct_sale_price }}

                    </div>
                <hr class="my-4 item-{{ item.pk }}">

{% endfor %}
                </div>
            </div>

</div>

{% if cart|length > 0 %}
    
<div class="row mt-2" id="checkout-total-div">
            <div class="col-12">
                <div class="row flex-row justify-content-center">

                    <div class="col-12 col-md-4">
                    </div>
                    <div class="col-6 col-md-4">
                       <strong class="float-right">Cart Total:</strong>
                    </div>
                    <div class="col-6 col-md-4">
                       <strong id="cart-total">${{ cart_total }}</strong>
                    </div>
                </div>
            </div>

</div>

<div class="row mt-2" id="checkout-button-div">
            <div class="col-12">
                <div class="row flex-row justify-content-center">

                    <div class="col-6 col-md-4">
                    </div>
                    <div class="col-12 col-md-8">
                        <div class="row justify-content-center">

        <form action="{% url 'shop:checkout' %}" method="post" class="checkout-form">
            {% csrf_token %}
            <input type="hidden" name="checkout-items" value="{{ request.session.cart }}">
            <button type="submit" class="checkout-button card-link btn btn-dark btn-inline w-md-25" > <span class="mx-md-5 mx-0"> Checkout Now </span> </button>
        </form>



                    </div>
                    </div>
                </div>
            </div>

</div>

{% else %}
<div class="row mt-2">
            <div class="col-12">
                <div class="row flex-row justify-content-center">


<p>There are no items in your cart.</p>


                </div>
            </div>

</div>{% endif %}



            <hr class="my-4">
            
            <div class="row">
                <div class="col text-center">
                    {% if 'gallery' in request.META.HTTP_REFERER %}
                    <p><a href="{{request.META.HTTP_REFERER}}">Return to gallery</a></p>
                    {% else %}
                    <p><a href="/shop/">Return to the shop</a></p>
                    {% endif %}
                </div>
            </div>
       </div>
   </div>
</div>
{% endblock %}

shop/templates/shop/checkout.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags static widget_tweaks %}
{% block body_class %}template-gallerypage{% endblock %}


{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/loader.css' %}">


{% endblock %}
{% block extra_header_js %}
<!-- Load the client component. -->
<script src="https://js.braintreegateway.com/web/3.65.0/js/client.min.js"></script>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>


<!-- Load the PayPal Checkout component. -->
<script src="https://js.braintreegateway.com/web/3.65.0/js/paypal-checkout.min.js"></script>
  <script src="https://js.braintreegateway.com/web/dropin/1.24.0/js/dropin.min.js"></script>


{% endblock %}


{% block content %}

<div class="container">
    <div class="row ">

        <div class="col-12 ">
            <div class="row">
                <div class="col text-center">
                    <h1 class="page-title">Checkout</h1>
                </div>
            </div>

            <hr class="my-4">
            <div class="row">
                <div class="col-12">

                    <div class="row flex-row justify-content-center">
                    
     


<div class="panel-group mb-3" id="accordion">
  <div class="card">
    <div class="card-header justify-content-center text-center" id="headingOne">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          <strong>Order total: ${{ order_total }}</strong> 
      </h4> 
        </a>
&nbsp;
<span class="text-muted" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-question-circle-fill d-inline" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                          <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.496 6.033a.237.237 0 0 1-.24-.247C5.35 4.091 6.737 3.5 8.005 3.5c1.396 0 2.672.73 2.672 2.24 0 1.08-.635 1.594-1.244 2.057-.737.559-1.01.768-1.01 1.486v.105a.25.25 0 0 1-.25.25h-.81a.25.25 0 0 1-.25-.246l-.004-.217c-.038-.927.495-1.498 1.168-1.987.59-.444.965-.736.965-1.371 0-.825-.628-1.168-1.314-1.168-.803 0-1.253.478-1.342 1.134-.018.137-.128.25-.266.25h-.825zm2.325 6.443c-.584 0-1.009-.394-1.009-.927 0-.552.425-.94 1.01-.94.609 0 1.028.388 1.028.94 0 .533-.42.927-1.029.927z"></path>
                        </svg>

        show order details</span>
    </div>
    <div id="collapseOne" class="collapse in">
      <div class="card-body">


                    <div class="row flex-row justify-content-center">

{% for item in cart %}
                    
                    <div class="col-3 col-sm-2 col-md-2 m-3">
                        <div class="row justify-content-center">
                            {% image item.main_image fill-75x75 class="float-right img-fluid" %}
                        </div>
                        <div class="row justify-content-center">
                            <p> {{ item.title }} </p>
                        </div>
                        <div class="row justify-content-center">
                            <p> ${{ item.direct_sale_price }} </p>
                        </div>
                    </div>

{% endfor %}

    </div>


      </div>
    </div>
  </div>
</div>

                    


                </div>


                <form id="order-form" onsubmit="return false">

                        <div class="row flex-row justify-content-center mb-3">
                            <div class="col-3 float-right text-right">
                                Choose a shipping address:
                            </div>
                            <div class="col-9 col-md-5 float-left">
                                <div class="row">
                                    <select class="form-control w-100 w-md-50" id="address-select">
                                        <option hidden disabled selected value> -- select an option -- </option>
                                    {% for adr in user_addresses %}
                                        <option value="{{ adr.id }}">{{adr.formatted}}</option>
                                    {% endfor %}
                                    </select>
                                </div>
                                <div class="row text-right float-right">
                                    <a href="#" id="edit-address" class="collapse in ">Change address</a>
                                </div>
                            </div>
                            <div class="col-3 d-none d-md-block">
                            </div>

                        </div>
                    </form>

                    <form method="post" id="add-address-form" onsubmit="return false">
                        <div class="row flex-row justify-content-center mb-3">
                            <div class="col-12 col-md-3 float-none text-center float-md-right text-md-right collapse show " id="add-address-button">
                                - or - <a data-toggle="collapse" aria-expanded="false" data-target=".collapseTwo" aria-controls="geo-address geo-address-2 geo-address-submit" > <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/></svg> add a new adress</a>
                            </div>
                            <div class="col-9 col-md-5 float-left collapse in collapseTwo" id="geo-address">
                                {% csrf_token %}

                                {% for field in address_form %}
                                     <div class="fieldWrapper" id="places-result">
                                    {{ field.errors }}
                                    Street Address:
                                    {{ field|add_class:"form-control w-100" }}

                                    </div>
                                {% endfor %}
                                <div class="add-address-errors"></div>
                            </div>
                            <div class="col-3 d-none d-md-block">
                            </div>
                        </div>
                        <div class="row flex-row justify-content-center mb-3 collapse in collapseTwo" id="geo-address-2">

                            <div class="col-12 col-md-3 ">
                            </div>

                            <div class="col-9 col-md-5 ">
                                Apt/Unit/Suite/etc. (optional) <input type="text" name="address2" class="form-control" />
                            </div>

                            <div class="col-3 d-none d-md-block">
                            </div>
                        </div>
                        <div class="row flex-row justify-content-center mb-3 collapse in collapseTwo" id="geo-address-submit">
                            <div class="col-12 col-md-4">
                                <button class="btn btn-dark d-inline">Use this address</button>
                            </div>
                        </div>
                    </form>
                    <div class="row flex-row justify-content-center">
                        
                        <div class="loader">
                            <div class="loader-inner ball-pulse d-none" id="dropin-loading">
                              <div></div>
                              <div></div>
                              <div></div>
                            </div>
                        </div>
                    </div>
                    <div class="row flex-row justify-content-center d-none" id="dropin-wrapper">
                        <div id="dropin-container"></div>
                    </div>
                    <div class="d-none" id="braintree-submit-div">
                        <form id="braintree-submit-form" method="post" action="{% url 'shop:payment' %}">
                            {% csrf_token %}

                            <div class="row flex-row justify-content-center mb-1">
                                <div class="col-12 text-center">
                                   <strong> Ship to: </strong>
                                </div>
                            </div>

                            <div class="row flex-row justify-content-center mt-5">
                                <div class="col-3 float-right text-right">
                                    First name:
                                </div>
                                <div class="col-9 col-md-5">
                                    <input type="text" name="first-name" class="form-control" value="{{ request.user.first_name}}" required />
                                </div>
                                <div class="col-3 d-none d-md-block">
                                </div>
                                <div class="col-3 float-right text-right">
                                    Last name:
                                </div>
                                <div class="col-9 col-md-5">
                                    <input type="text" name="last-name" class="form-control" value="{{ request.user.last_name}}" required />
                                </div>
                                <div class="col-3 d-none d-md-block">
                                </div>

                                {# hidden inputs #}
                                <input type="hidden" name="order-total" value="{{ order_total }}" />
                            </div>
                            <div class="row flex-row justify-content-center my-3">
                                <div class="g-recaptcha" data-sitekey="6LfZBNEZAAAAADd_O2E062BP0IDTIt4lz5hi4NQN"></div>
                            </div>

                            <div class="row flex-row justify-content-center mb-3">


                                <button id="braintree-submit-button" type="submit" value="Submit" class="btn btn-dark ">Complete Purchase</button>

                                <div class="loader d-none" id="checkout-submit-loader">
                                    <div class="loader-inner ball-pulse">
                                      <div></div>
                                      <div></div>
                                      <div></div>
                                    </div>
                                </div>


                            </div>
                        </form>

                    </div>
     
                </div>
            </div>
        </div>
    </div>
</div>

  <script>
    var braintree_client_token = "{{ braintree_client_token }}";
    var order_total = {{ order_total }}
    var csrf_token = '{{ csrf_token }}';
   
    </script>


{% endblock %}

{% block extra_js %}
                    {{ address_form.media }} <!-- needed for JS/GoogleMaps lookup -->

<script src="{% static 'js/braintree.js' %}"></script>
{% endblock %}
    

shop/templates/shop/shop_item_ajax.html
Hello world, 

TESTSTETSTT